name: Release Prompt List

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      
      - name: Setup Python 3.9.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.4
      
      - name: Install Requirements
        run: pip install -r requirements.txt
      
      - name: Run scraper.py
        env:
          CI: ${{ secrets.CLIENT_ID }}
          CS: ${{ secrets.CLIENT_SECRET }}
        run: |
          python scraper.py --client-id "$CI" --client-secret "$CS" --outfile test.csv
